# Generated by Django 5.1.7 on 2025-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='federation_type',
            field=models.CharField(choices=[('MONDIAL', 'Mondial'), ('CONTINENTAL', 'Continental'), ('NATIONAL', 'National')], default='NATIONAL', max_length=15),
        ),
    ]
