# Generated by Django 5.1.7 on 2025-04-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upaloads/tournaments/logos')),
                ('tournament_type', models.CharField(choices=[('LEAGUE', 'League'), ('COMPETITION', 'Competition')], max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=1)),
                ('is_national', models.BooleanField(default=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='federations.federation')),
            ],
        ),
    ]
