# Generated by Django 5.1.7 on 2025-04-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
